In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [2]:
df=pd.read_csv('Squad Matching data.csv',parse_dates = True,encoding='latin-1')
df.head(20)

,Name,Squad Number,Do you have any preferred language of communication?,What Group Virtual Internship Program are you interested in registering for,Age,City,Country,Region,Time Zone,current occupation?,...,Product Design,Product Development,Growth Marketing,Leading groups,Where did you hear about this internship?,Which cohorts are you available to start the Product Marketing Internship?,Which cohorts are you available to start the Product Design Internship?,Which cohorts are you available to start the Product Development Internship?,Which cohorts are you available to start the Product Growth Internship?,How many hours per week are you able to give to the internship program?
0,Grayson,NaN,i prefer english but i am also able to communi...,"Product Marketing,Product Growth",23.0,bordj bou arreridj,Algeria,MENA,"Europe,Africa",Recently Graduated and Unemployed,...,NaN,NaN,4.0,NaN,linkedin,"Starting on 15th August,Starting on 22nd August",NaN,NaN,Starting on 5th September,20-25 hours
1,Jonas,NaN,English,"Product Marketing,Product Growth ,Product Design",23.0,Algiers,Algeria,MENA,"Africa,Europe",Recently Graduated and Unemployed,...,3.0,NaN,4.0,4.0,Linkedin,"Starting on 12th September,Starting on 15th Au...","Starting on 3rd October,Starting on 22nd August",NaN,Starting on 3rd October,10-15 hours
2,Ronan,NaN,English and Spanish are good for me.,Product Design,34.0,"Buenos Aires, Argentina",Argentina,Americas,Americas,Employed,...,4.0,NaN,NaN,5.0,A friend told me about it.,NaN,Starting on 22nd August,NaN,NaN,15-20 hours
3,Dulce,NaN,spanish,Product Design,38.0,Mendoza,Argentina,Americas,Americas,Employed,...,3.0,NaN,NaN,4.0,Linkedin,NaN,Starting on 22nd August,NaN,NaN,20-25 hours
4,Evelyn,NaN,Spanish,Product Marketing,22.0,Tigre,Argentina,Americas,Any/No preference,Recently Graduated and Unemployed,...,NaN,NaN,NaN,4.0,Linkedin,"Starting on 22nd August,Starting on 15th August",NaN,NaN,NaN,20-25 hours
5,Rocco,NaN,English,"Product Growth ,Product Development",21.0,Buenos Aires,Argentina,Americas,Americas,University Student,...,3.0,4.0,3.0,NaN,LinkedIn,NaN,NaN,Starting on 3rd October,I would prefer a later cohort,10-15 hours
6,Everett,NaN,Español,"Product Design,Product Marketing",34.0,Junín,Argentina,Americas,"Americas,Europe,Australia",Employed,...,1.0,NaN,NaN,NaN,Linkedin,I would prefer a later cohort,Starting on 3rd October,NaN,NaN,10-15 hours
7,Patrick,NaN,English is okay,"Product Design,Product Development",25.0,Yerevan,Armenia,Europe,"Asia,Europe",Currently Unemployed,...,3.0,1.0,NaN,5.0,on LinkedIn,NaN,"Starting on 22nd August,Starting on 5th September",Starting on 5th September,NaN,10-15 hours
8,Beau,NaN,English Russians,Product Design,24.0,Yerevan,Armenia,Europe,Europe,Recently Graduated and Unemployed,...,5.0,NaN,NaN,4.0,LinkedIn,NaN,Starting on 22nd August,NaN,NaN,20-25 hours
9,Valerie,NaN,french,Product Design,33.0,Vienna,Autriche,Europe,Europe,Currently Unemployed,...,2.0,NaN,NaN,2.0,Friend of mine give me the website,NaN,Starting on 22nd August,NaN,NaN,10-15 hours
10,Noemi,NaN,English,Product Design,19.0,Baku,Azerbaijan,Europe,Asia,University Student,...,4.0,NaN,NaN,3.0,From linkedin,NaN,Starting on 5th September,NaN,NaN,15-20 hours
11,Rosie,NaN,"English (I speak Azerbaijani, Russian)",Product Design,33.0,Baku,Azerbaijan,Europe,"Europe,Africa,Asia",Currently Unemployed,...,1.0,NaN,NaN,NaN,LinkedIn,NaN,Starting on 5th September,NaN,NaN,20-25 hours
12,Khaleesi,NaN,No,Product Development,24.0,Cumilla,Bangladesh,APAC,Asia,Currently Unemployed,...,5.0,3.0,NaN,4.0,LinkedIn,NaN,NaN,Starting on 5th September,NaN,15-20 hours
13,Arya,NaN,English,Product Design,19.0,Dhaka,Bangladesh,APAC,Asia,University Student,...,5.0,NaN,NaN,4.0,I learned about this internship through LinkedIn,NaN,Starting on 22nd August,NaN,NaN,10-15 hours
14,Taylor,NaN,English,Product Marketing,36.0,Sylhet,Bangladesh,APAC,Asia,Currently Unemployed,...,NaN,NaN,NaN,1.0,For get a ideal job,Starting on 22nd August,NaN,NaN,NaN,10-15 hours
15,Oliver,NaN,"English, Hindi, Bangla","Product Design,Product Development",24.0,Dhaka,Bangladesh,APAC,Asia,Employed,...,4.0,1.0,NaN,4.0,LinkedIn,NaN,Starting on 22nd August,I would prefer a later cohort,NaN,10-15 hours
16,Enrique,NaN,English,Product Marketing,21.0,"Dhaka, Dhaka Division, Bangladesh",Bangladesh,APAC,Asia,University Student,...,NaN,NaN,NaN,3.0,Indeed,Starting on 15th August,NaN,NaN,NaN,20-25 hours
17,Ibrahim,NaN,English,Product Development,23.0,Dhaka,Bangladesh,APAC,"Asia,Americas",University Student,...,3.0,4.0,NaN,5.0,From LinkedIN,NaN,NaN,Starting on 5th September,NaN,15-20 hours
18,Jaylen,NaN,Bangla,Product Development,23.0,Dhaka,Bangladesh,APAC,Asia,University Student,...,1.0,3.0,NaN,3.0,Linkedin,NaN,NaN,I would prefer a later cohort,NaN,15-20 hours
19,Paisley,NaN,no,"Product Marketing,Product Growth",24.0,sylhet,Bangladesh,APAC,Any/No preference,Recently Graduated and Unemployed,...,NaN,NaN,4.0,4.0,Linkedin,"Starting on 15th August,Starting on 22nd August",NaN,NaN,Starting on 5th September,15-20 hours

In [3]:
df.isnull().sum()

Name                                                                               0
Squad Number                                                                    1188
Do you have any preferred language of communication?                              19
What Group Virtual Internship Program are you interested in registering for        1
Age                                                                                0
City                                                                               0
Country                                                                            0
Region                                                                             4
Time Zone                                                                          0
current occupation?                                                                0
What did you study at University/College?                                          4
Upskilling courses on online platforms like Udemy, Coursera, edX, or others?       1
Do you have any previous work or internship experience?                            1
Product Management                                                                 1
Digital Marketing                                                                709
Market Research                                                                  220
Digital Illustration                                                             303
Product Design                                                                   265
Product Development                                                              661
Growth Marketing                                                                 888
Leading groups                                                                   689
Where did you hear about this internship?                                          0
Which cohorts are you available to start the Product Marketing Internship?       716
Which cohorts are you available to start the Product Design Internship?          587
Which cohorts are you available to start the Product Development Internship?     662
Which cohorts are you available to start the Product Growth Internship?          889
How many hours per week are you able to give to the internship program?            0
dtype: int64

In [4]:

df['What Group Virtual Internship Program are you interested in registering for'] = df['What Group Virtual Internship Program are you interested in registering for'].str.split(',').str[0]

In [5]:
df['What Group Virtual Internship Program are you interested in registering for']

0         Product Marketing
1         Product Marketing
2            Product Design
3            Product Design
4         Product Marketing
               ...
1183    Product Development
1184    Product Development
1185         Product Design
1186      Product Marketing
1187    Product Development
Name: What Group Virtual Internship Program are you interested in registering for, Length: 1188, dtype: object

# DATA CLEANING FOR REGION & TIMEZONE

In [6]:
#collecting Region data contain null values
#df2 = Region data contain null values
df1=pd.isnull(df["Region"])
df2=df[df1]
df2

,Name,Squad Number,Do you have any preferred language of communication?,What Group Virtual Internship Program are you interested in registering for,Age,City,Country,Region,Time Zone,current occupation?,...,Product Design,Product Development,Growth Marketing,Leading groups,Where did you hear about this internship?,Which cohorts are you available to start the Product Marketing Internship?,Which cohorts are you available to start the Product Design Internship?,Which cohorts are you available to start the Product Development Internship?,Which cohorts are you available to start the Product Growth Internship?,How many hours per week are you able to give to the internship program?
139,Reyansh,NaN,"English , Arabic",Product Development,22.0,Cairo,Egypt,NaN,"Africa,Any/No preference,Europe,Americas",University Student,...,1.0,4.0,NaN,NaN,College friends,NaN,NaN,Starting on 3rd October,NaN,20-25 hours
220,Lola,NaN,English,Product Design,19.0,Pune,India,NaN,"Asia,Europe,Australia,Africa,Any/No preference",University Student,...,3.0,3.0,4.0,NaN,LinkedIn,NaN,Starting on 5th September,Starting on 5th September,Starting on 5th September,15-20 hours
519,Gavin,NaN,English,Product Development,18.0,Lagos,Nigeria,NaN,Africa,University Student,...,1.0,3.0,NaN,NaN,I heard about this internship fron a colleague...,NaN,NaN,Starting on 5th September,NaN,15-20 hours
798,Giselle,NaN,English,Product Development,27.0,East London,South Africa,NaN,"Africa,Europe",University Student,...,1.0,1.0,NaN,NaN,LinkedIn,NaN,NaN,Starting on 5th September,NaN,20-25 hours

In [7]:
df2['Time Zone']

139          Africa,Any/No preference,Europe,Americas
220    Asia,Europe,Australia,Africa,Any/No preference
519                                            Africa
798                                     Africa,Europe
Name: Time Zone, dtype: object

In [8]:
#splliting the data using delimeter and extacting(storing) the first string
df2['Time Zone']= df2['Time Zone'].str.split(',').str[0]
df2['Time Zone']

C:\Users\KURELL~1.VAR\AppData\Local\Temp/ipykernel_14420/1719050874.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['Time Zone']= df2['Time Zone'].str.split(',').str[0]

139    Africa
220      Asia
519    Africa
798    Africa
Name: Time Zone, dtype: object

In [9]:
#Based on the Time zone replacing all the null values in the Region
df2['Region']=df2["Time Zone"]
df2['Region'] = df2['Region'].replace(['Africa','Asia'],['MENA','APAC'])

df2['Region']

C:\Users\KURELL~1.VAR\AppData\Local\Temp/ipykernel_14420/1801225476.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['Region']=df2["Time Zone"]
C:\Users\KURELL~1.VAR\AppData\Local\Temp/ipykernel_14420/1801225476.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['Region'] = df2['Region'].replace(['Africa','Asia'],['MENA','APAC'])

139    MENA
220    APAC
519    MENA
798    MENA
Name: Region, dtype: object

In [10]:
# Regions and Timezones are replaced properly

print(df2)

        Name  Squad Number  \
139  Reyansh           NaN
220     Lola           NaN
519    Gavin           NaN
798  Giselle           NaN

    Do you have any preferred language of communication?  \
139                                   English , Arabic
220                                            English
519                                            English
798                                            English

    What Group Virtual Internship Program are you interested in registering for  \
139                                Product Development
220                                     Product Design
519                                Product Development
798                                Product Development

      Age         City       Country Region Time Zone current occupation?  \
139  22.0        Cairo         Egypt   MENA    Africa  University Student
220  19.0         Pune         India   APAC      Asia  University Student
519  18.0        Lagos       Nigeria   MENA    Africa  University Student
798  27.0  East London  South Africa   MENA    Africa  University Student

     ... Product Design Product Development Growth Marketing  Leading groups  \
139  ...            1.0                 4.0              NaN             NaN
220  ...            3.0                 3.0              4.0             NaN
519  ...            1.0                 3.0              NaN             NaN
798  ...            1.0                 1.0              NaN             NaN

             Where did you hear about this internship?  \
139                                    College friends
220                                           LinkedIn
519  I heard about this internship fron a colleague...
798                                           LinkedIn

     Which cohorts are you available to start the Product Marketing Internship?  \
139                                                NaN
220                                                NaN
519                                                NaN
798                                                NaN

     Which cohorts are you available to start the Product Design Internship?  \
139                                                NaN
220                          Starting on 5th September
519                                                NaN
798                                                NaN

     Which cohorts are you available to start the Product Development Internship?  \
139                            Starting on 3rd October
220                          Starting on 5th September
519                          Starting on 5th September
798                          Starting on 5th September

     Which cohorts are you available to start the Product Growth Internship?  \
139                                                NaN
220                          Starting on 5th September
519                                                NaN
798                                                NaN

     How many hours per week are you able to give to the internship program?
139                                        20-25 hours
220                                        15-20 hours
519                                        15-20 hours
798                                        20-25 hours

[4 rows x 27 columns]

In [11]:
df['Time Zone']=df["Region"]
#df['Time Zone']
df['Time Zone'] = df['Time Zone'].replace(['APAC','MENA'],['Asia','Africa'])
df['Time Zone']

0         Africa
1         Africa
2       Americas
3       Americas
4       Americas
          ...
1183    Americas
1184    Americas
1185    Americas
1186        Asia
1187        Asia
Name: Time Zone, Length: 1188, dtype: object

In [12]:
df

,Name,Squad Number,Do you have any preferred language of communication?,What Group Virtual Internship Program are you interested in registering for,Age,City,Country,Region,Time Zone,current occupation?,...,Product Design,Product Development,Growth Marketing,Leading groups,Where did you hear about this internship?,Which cohorts are you available to start the Product Marketing Internship?,Which cohorts are you available to start the Product Design Internship?,Which cohorts are you available to start the Product Development Internship?,Which cohorts are you available to start the Product Growth Internship?,How many hours per week are you able to give to the internship program?
0,Grayson,NaN,i prefer english but i am also able to communi...,Product Marketing,23.0,bordj bou arreridj,Algeria,MENA,Africa,Recently Graduated and Unemployed,...,NaN,NaN,4.0,NaN,linkedin,"Starting on 15th August,Starting on 22nd August",NaN,NaN,Starting on 5th September,20-25 hours
1,Jonas,NaN,English,Product Marketing,23.0,Algiers,Algeria,MENA,Africa,Recently Graduated and Unemployed,...,3.0,NaN,4.0,4.0,Linkedin,"Starting on 12th September,Starting on 15th Au...","Starting on 3rd October,Starting on 22nd August",NaN,Starting on 3rd October,10-15 hours
2,Ronan,NaN,English and Spanish are good for me.,Product Design,34.0,"Buenos Aires, Argentina",Argentina,Americas,Americas,Employed,...,4.0,NaN,NaN,5.0,A friend told me about it.,NaN,Starting on 22nd August,NaN,NaN,15-20 hours
3,Dulce,NaN,spanish,Product Design,38.0,Mendoza,Argentina,Americas,Americas,Employed,...,3.0,NaN,NaN,4.0,Linkedin,NaN,Starting on 22nd August,NaN,NaN,20-25 hours
4,Evelyn,NaN,Spanish,Product Marketing,22.0,Tigre,Argentina,Americas,Americas,Recently Graduated and Unemployed,...,NaN,NaN,NaN,4.0,Linkedin,"Starting on 22nd August,Starting on 15th August",NaN,NaN,NaN,20-25 hours
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1183,Johnathan,NaN,English,Product Development,22.0,"Las Cruces, New Mexico",USA,Americas,Americas,Recently Graduated and Unemployed,...,1.0,4.0,2.0,NaN,LinkedIn,NaN,NaN,Starting on 5th September,Starting on 5th September,20-25 hours
1184,Adriel,NaN,English is the language I am most comfortable ...,Product Development,19.0,seattle,USA,Americas,Americas,University Student,...,1.0,3.0,NaN,NaN,I saw it on linkedin.,NaN,NaN,Starting on 5th September,NaN,15-20 hours
1185,Reyna,NaN,English,Product Design,30.0,Caracas,Venezuela,Americas,Americas,Employed,...,5.0,NaN,NaN,4.0,LinkedIn,NaN,"Starting on 5th September,Starting on 22nd August",NaN,NaN,10-15 hours
1186,Uriel,NaN,English,Product Marketing,21.0,Hanoi,Vietnam,APAC,Asia,University Student,...,3.0,NaN,1.0,3.0,I saw this on LinkedIn,Starting on 15th August,Starting on 22nd August,NaN,Starting on 5th September,15-20 hours
1187,Esteban,NaN,Vietnamese,Product Development,23.0,Ho Chi Minh,Vietnam,APAC,Asia,University Student,...,2.0,4.0,NaN,NaN,Linkedln,NaN,NaN,Starting on 5th September,NaN,10-15 hours

In [13]:
# df2 values are storing in the main dataframe (df)
df.loc[df2.index, :] = df2[:]

In [14]:
df

,Name,Squad Number,Do you have any preferred language of communication?,What Group Virtual Internship Program are you interested in registering for,Age,City,Country,Region,Time Zone,current occupation?,...,Product Design,Product Development,Growth Marketing,Leading groups,Where did you hear about this internship?,Which cohorts are you available to start the Product Marketing Internship?,Which cohorts are you available to start the Product Design Internship?,Which cohorts are you available to start the Product Development Internship?,Which cohorts are you available to start the Product Growth Internship?,How many hours per week are you able to give to the internship program?
0,Grayson,NaN,i prefer english but i am also able to communi...,Product Marketing,23.0,bordj bou arreridj,Algeria,MENA,Africa,Recently Graduated and Unemployed,...,NaN,NaN,4.0,NaN,linkedin,"Starting on 15th August,Starting on 22nd August",NaN,NaN,Starting on 5th September,20-25 hours
1,Jonas,NaN,English,Product Marketing,23.0,Algiers,Algeria,MENA,Africa,Recently Graduated and Unemployed,...,3.0,NaN,4.0,4.0,Linkedin,"Starting on 12th September,Starting on 15th Au...","Starting on 3rd October,Starting on 22nd August",NaN,Starting on 3rd October,10-15 hours
2,Ronan,NaN,English and Spanish are good for me.,Product Design,34.0,"Buenos Aires, Argentina",Argentina,Americas,Americas,Employed,...,4.0,NaN,NaN,5.0,A friend told me about it.,NaN,Starting on 22nd August,NaN,NaN,15-20 hours
3,Dulce,NaN,spanish,Product Design,38.0,Mendoza,Argentina,Americas,Americas,Employed,...,3.0,NaN,NaN,4.0,Linkedin,NaN,Starting on 22nd August,NaN,NaN,20-25 hours
4,Evelyn,NaN,Spanish,Product Marketing,22.0,Tigre,Argentina,Americas,Americas,Recently Graduated and Unemployed,...,NaN,NaN,NaN,4.0,Linkedin,"Starting on 22nd August,Starting on 15th August",NaN,NaN,NaN,20-25 hours
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1183,Johnathan,NaN,English,Product Development,22.0,"Las Cruces, New Mexico",USA,Americas,Americas,Recently Graduated and Unemployed,...,1.0,4.0,2.0,NaN,LinkedIn,NaN,NaN,Starting on 5th September,Starting on 5th September,20-25 hours
1184,Adriel,NaN,English is the language I am most comfortable ...,Product Development,19.0,seattle,USA,Americas,Americas,University Student,...,1.0,3.0,NaN,NaN,I saw it on linkedin.,NaN,NaN,Starting on 5th September,NaN,15-20 hours
1185,Reyna,NaN,English,Product Design,30.0,Caracas,Venezuela,Americas,Americas,Employed,...,5.0,NaN,NaN,4.0,LinkedIn,NaN,"Starting on 5th September,Starting on 22nd August",NaN,NaN,10-15 hours
1186,Uriel,NaN,English,Product Marketing,21.0,Hanoi,Vietnam,APAC,Asia,University Student,...,3.0,NaN,1.0,3.0,I saw this on LinkedIn,Starting on 15th August,Starting on 22nd August,NaN,Starting on 5th September,15-20 hours
1187,Esteban,NaN,Vietnamese,Product Development,23.0,Ho Chi Minh,Vietnam,APAC,Asia,University Student,...,2.0,4.0,NaN,NaN,Linkedln,NaN,NaN,Starting on 5th September,NaN,10-15 hours

In [15]:

df.isnull().sum()

Name                                                                               0
Squad Number                                                                    1188
Do you have any preferred language of communication?                              19
What Group Virtual Internship Program are you interested in registering for        1
Age                                                                                0
City                                                                               0
Country                                                                            0
Region                                                                             0
Time Zone                                                                          0
current occupation?                                                                0
What did you study at University/College?                                          4
Upskilling courses on online platforms like Udemy, Coursera, edX, or others?       1
Do you have any previous work or internship experience?                            1
Product Management                                                                 1
Digital Marketing                                                                709
Market Research                                                                  220
Digital Illustration                                                             303
Product Design                                                                   265
Product Development                                                              661
Growth Marketing                                                                 888
Leading groups                                                                   689
Where did you hear about this internship?                                          0
Which cohorts are you available to start the Product Marketing Internship?       716
Which cohorts are you available to start the Product Design Internship?          587
Which cohorts are you available to start the Product Development Internship?     662
Which cohorts are you available to start the Product Growth Internship?          889
How many hours per week are you able to give to the internship program?            0
dtype: int64

# Data Cleaning for Prefrred language

In [16]:
#using Regex pattern we are storing  the first prefrred language of the person

df['Do you have any preferred language of communication?']=df['Do you have any preferred language of communication?'].replace(to_replace='.*[Ee,]n.*', value= 'English', regex= True)  
df['Do you have any preferred language of communication?']=df['Do you have any preferred language of communication?'].replace(to_replace='.*[Aa,]r.*', value= 'Arabic', regex= True)  
df['Do you have any preferred language of communication?']=df['Do you have any preferred language of communication?'].replace(to_replace='.*[eE,]N.*', value= 'English', regex= True)  
df['Do you have any preferred language of communication?']=df['Do you have any preferred language of communication?'].replace(to_replace='.*[Bb,]a.*', value= 'Bahasa', regex= True)  
df['Do you have any preferred language of communication?']=df['Do you have any preferred language of communication?'].replace(to_replace='.*[Uu,]r.*', value= 'Urdu', regex= True)
df['Do you have any preferred language of communication?']=df['Do you have any preferred language of communication?'].replace(to_replace='.*[Uu,]k.*', value= 'Ukranian', regex= True)  
df['Do you have any preferred language of communication?']=df['Do you have any preferred language of communication?'].replace(to_replace='.*[Tt,]a.*', value= 'Tamil', regex= True)  
df['Do you have any preferred language of communication?']=df['Do you have any preferred language of communication?'].replace(to_replace='.*[Pp,]a.*', value= 'Punjabi', regex= True)  
df['Do you have any preferred language of communication?']=df['Do you have any preferred language of communication?'].replace(to_replace='.*[Hh,]i.*', value= 'Hindi', regex= True)

In [17]:
df

,Name,Squad Number,Do you have any preferred language of communication?,What Group Virtual Internship Program are you interested in registering for,Age,City,Country,Region,Time Zone,current occupation?,...,Product Design,Product Development,Growth Marketing,Leading groups,Where did you hear about this internship?,Which cohorts are you available to start the Product Marketing Internship?,Which cohorts are you available to start the Product Design Internship?,Which cohorts are you available to start the Product Development Internship?,Which cohorts are you available to start the Product Growth Internship?,How many hours per week are you able to give to the internship program?
0,Grayson,NaN,English,Product Marketing,23.0,bordj bou arreridj,Algeria,MENA,Africa,Recently Graduated and Unemployed,...,NaN,NaN,4.0,NaN,linkedin,"Starting on 15th August,Starting on 22nd August",NaN,NaN,Starting on 5th September,20-25 hours
1,Jonas,NaN,English,Product Marketing,23.0,Algiers,Algeria,MENA,Africa,Recently Graduated and Unemployed,...,3.0,NaN,4.0,4.0,Linkedin,"Starting on 12th September,Starting on 15th Au...","Starting on 3rd October,Starting on 22nd August",NaN,Starting on 3rd October,10-15 hours
2,Ronan,NaN,English,Product Design,34.0,"Buenos Aires, Argentina",Argentina,Americas,Americas,Employed,...,4.0,NaN,NaN,5.0,A friend told me about it.,NaN,Starting on 22nd August,NaN,NaN,15-20 hours
3,Dulce,NaN,Punjabi,Product Design,38.0,Mendoza,Argentina,Americas,Americas,Employed,...,3.0,NaN,NaN,4.0,Linkedin,NaN,Starting on 22nd August,NaN,NaN,20-25 hours
4,Evelyn,NaN,Punjabi,Product Marketing,22.0,Tigre,Argentina,Americas,Americas,Recently Graduated and Unemployed,...,NaN,NaN,NaN,4.0,Linkedin,"Starting on 22nd August,Starting on 15th August",NaN,NaN,NaN,20-25 hours
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1183,Johnathan,NaN,English,Product Development,22.0,"Las Cruces, New Mexico",USA,Americas,Americas,Recently Graduated and Unemployed,...,1.0,4.0,2.0,NaN,LinkedIn,NaN,NaN,Starting on 5th September,Starting on 5th September,20-25 hours
1184,Adriel,NaN,English,Product Development,19.0,seattle,USA,Americas,Americas,University Student,...,1.0,3.0,NaN,NaN,I saw it on linkedin.,NaN,NaN,Starting on 5th September,NaN,15-20 hours
1185,Reyna,NaN,English,Product Design,30.0,Caracas,Venezuela,Americas,Americas,Employed,...,5.0,NaN,NaN,4.0,LinkedIn,NaN,"Starting on 5th September,Starting on 22nd August",NaN,NaN,10-15 hours
1186,Uriel,NaN,English,Product Marketing,21.0,Hanoi,Vietnam,APAC,Asia,University Student,...,3.0,NaN,1.0,3.0,I saw this on LinkedIn,Starting on 15th August,Starting on 22nd August,NaN,Starting on 5th September,15-20 hours
1187,Esteban,NaN,Vietnamese,Product Development,23.0,Ho Chi Minh,Vietnam,APAC,Asia,University Student,...,2.0,4.0,NaN,NaN,Linkedln,NaN,NaN,Starting on 5th September,NaN,10-15 hours

# LABEL ENCODING

In [18]:
labelencoder = LabelEncoder()

#df['Do you have any preferred language of communication?'] = labelencoder.fit_transform(df['Do you have any preferred language of communication?'])
df['Country'] = labelencoder.fit_transform(df['Country'])
df['Region'] = labelencoder.fit_transform(df['Region'])
df['Time Zone'] = labelencoder.fit_transform(df['Time Zone'])

In [19]:
df.to_csv('final data.csv')